### ISSUE TITLE
Possible bug with EORS

### ISSUE THREAD

**Issue by salmanarif** [cornell-brg/pydgin#22]
I have been running some tests using `arm-sim.py`, and it appears that an instruction of the form:
`EORS Rd, Rm, #n` always sets the carry bit. According to [documentation on the EOR instruction](http://www.keil.com/support/man/docs/armasm/armasm_dom1361289871065.htm), the carry bit should only be set if `n` can be created by shifting an 8-bit value.

**Comment by salmanarif** [comment]
Another possible issue is `ROR` instructions changing the carry bit in the following forms:
`RORS Rd, Rm, Rn    ; Rn == 0`

If the shift amount is `0`, nothing is shifted, so should the carry bit not be left unchanged?

**Comment by dmlockhart** [comment]
Hi @salmanarif, could you possibly provide me a test case where you are observing this behavior? Preferably a small assembly test.

Note that I'm basing my instruction implementations on the following document:
- http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0100i/index.html

A few follow up comments:
- ``RORS`` should be ``RORS Rd, Rm, Rs; Rs == 0``, the ``Rn`` field is not used.  You are correct the C flag should remain unchanged if ``Rs==0``.
- ``EORS`` should have it's carry bit set according to ``Rm[shift_imm - 1]``, where ``Rm == instruction_bits[0:4]`` and ``shift_imm == instruction_bits[7:12]`` (using Python index notation)

**Comment by dmlockhart** [comment]
@salmanarif I've added a few basic tests for ``EOR``, all are behaving as expected: the C flag is only set if the last bit shifted out is a 1.

These tests certainly aren't comprehensive, so if you can find a shift value that causes the C flag to be set to an incorrect value, let me know!

**Comment by salmanarif** [comment]
@dmlockhart Thank you for looking into it quickly. Here's a an example of `EORS` settings the carry bit without a shift:
```
#include "arm-macros.h"
TEST_BEGIN
ldr r0, =0xc5
ldr r1, =0x0
ldr r2, =0xc300000
eors r0, r0, r2
eors r0, r1, r2
eors r0, r1, #0xcb00000
eors r0, r1, #0xf0000000 
TEST_END
```

Log file using command `python arm-sim.py --debug insts,regdump out.elf`:
```
NOTE: Using sparse storage
sparse memory size 400 addr mask 3ff block mask fffffc00
XXX 3221209140
  8000 e3a000c5 mov      0       
0 :000000c5 1 :00000001 2 :bfffc004 3 :00000000 
4 :00000000 5 :00000000 6 :00000000 7 :00000000 
8 :00000000 9 :00000000 10:00000000 11:00000000 
12:00000000 13:bfffc000 14:00000000 15:00000000 
----
  8004 e3a01000 mov      1       
0 :000000c5 1 :00000000 2 :bfffc004 3 :00000000 
4 :00000000 5 :00000000 6 :00000000 7 :00000000 
8 :00000000 9 :00000000 10:00000000 11:00000000 
12:00000000 13:bfffc000 14:00000000 15:00000000 
----
  8008 e3a026c3 mov      2       
0 :000000c5 1 :00000000 2 :0c300000 3 :00000000 
4 :00000000 5 :00000000 6 :00000000 7 :00000000 
8 :00000000 9 :00000000 10:00000000 11:00000000 
12:00000000 13:bfffc000 14:00000000 15:00000000 
----
  800c e0300002 eor      3       
0 :0c3000c5 1 :00000000 2 :0c300000 3 :00000000 
4 :00000000 5 :00000000 6 :00000000 7 :00000000 
8 :00000000 9 :00000000 10:00000000 11:00000000 
12:00000000 13:bfffc000 14:00000000 15:00000000 
----
  8010 e0310002 eor      4       
0 :0c300000 1 :00000000 2 :0c300000 3 :00000000 
4 :00000000 5 :00000000 6 :00000000 7 :00000000 
8 :00000000 9 :00000000 10:00000000 11:00000000 
12:00000000 13:bfffc000 14:00000000 15:00000000 
----
  8014 e23106cb eor      5       
0 :0cb00000 1 :00000000 2 :0c300000 3 :00000000 
4 :00000000 5 :00000000 6 :00000000 7 :00000000 
8 :00000000 9 :00000000 10:00000000 11:00000000 
12:00000000 13:bfffc000 14:00000000 15:00000000 
--C-
  8018 e231020f eor      6       
0 :f0000000 1 :00000000 2 :0c300000 3 :00000000 
4 :00000000 5 :00000000 6 :00000000 7 :00000000 
8 :00000000 9 :00000000 10:00000000 11:00000000 
12:00000000 13:bfffc000 14:00000000 15:00000000 
N-C-
  801c e3a07001 mov      7       
0 :f0000000 1 :00000000 2 :0c300000 3 :00000000 
4 :00000000 5 :00000000 6 :00000000 7 :00000001 
8 :00000000 9 :00000000 10:00000000 11:00000000 
12:00000000 13:bfffc000 14:00000000 15:00000000 
N-C-
  8020 ef000000 swi      8       
0 :f0000000 1 :00000000 2 :0c300000 3 :00000000 
4 :00000000 5 :00000000 6 :00000000 7 :00000001 
8 :00000000 9 :00000000 10:00000000 11:00000000 
12:00000000 13:bfffc000 14:00000000 15:00000000 
N-C-
DONE! Status = 4026531840
Instructions Executed = 9
```

As you can see, on instructions 5 and 6, the carry bit is set to 1, even though no shift operation is being performed.

For the sake of completeness, I used the the [GNU Tools for ARM Embedded Processors](https://launchpad.net/gcc-arm-embedded) to cross-compile the binary file with the following flags:
`arm-none-eabi-gcc -marm -march=armv7-r -nostdlib test-00000.S -o out.elf`

Perhaps I should create a separate issue for this, but I have also noticed that `TEQ` also sets the carry flag if an immediate is used but a shift operation is not involved. Could these be related, since TEQ is like EOR, except that the result is discarded?

**Comment by dmlockhart** [comment]
Hi @salmanarif, even though you aren't explicitly performing a shift in your assembly, I believe the assembler is *implicitly* doing a shift in order to generate the constant ``#0xcb00000`` used in instruction 5.

If you look at instruction 5 (pc = 8014), we can see the bit encoding is ``0xe23106cb``:
```
  8014 e23106cb eor      5
```

Decoding the instruction bits of ``0xe23106cb`` looks something like this (pg. A4-32 in ARM manual):
 ```
  cond      I        S   Rn    Rd    shifter_op
  1110  00  1  0001  1  0100  0100  011011001011
```

Where ``shifter_op`` can be further decoded as (pg. A5-3 in ARM manual) :
```
  rotate_imm   imm_8
     0110     11001011
```

The manual states on pg. A5-6:

> The <shifter_operand> value is formed by rotating (to the right) an 8-bit immediate
> value to any even bit position in a 32-bit word. If the rotate immediate is zero,
> the carry-out from the shifter is the value of the C flag, otherwise, it is set to bit[31]
> of the value of <shifter_operand>.

And describes this instruction encoding as:
```
  shifter_operand = immed_8 Rotate_Right (rotate_imm * 2) 
  if rotate_imm == 0 then
       shifter_carry_out = C flag
  else /* rotate_imm != 0 */
       shifter_carry_out = shifter_operand[31]
```

So even though the immediate value you provided looks plain, it's generated by secretly shifting the value ``0xcb`` to the right 6*2 positions.

However, it seems you are correct in that the C Flag computation is incorrect.  The MSB of the shifter_operand should be 0 after this operation, so the C Flag should be set to zero. QEMU seems to confirm this.

I'll look into fixing this bug tomorrow (hopefully).

**Comment by dmlockhart** [comment]
Nevermind, it was a super easy one line fix. This should hopefully address the problem for all instructions using 32 bit immediate!

Please let me know if this change breaks anything, we don't have a great regression test setup right now.

**Comment by salmanarif** [comment]
It does not seem to have broken anything else, however, `TEQ` and `TST` instructions are setting the carry bit even if the second operand does not have a rotate or `bit[31]` as `1`. Should these not have the same behaviour as other instructions, now that you have fixed the issue with 32-bit immediates?
