### ISSUE TITLE
A base class for State would be useful

### ISSUE THREAD

**Issue by snim2** [cornell-brg/pydgin#23]
State expects a number of fields, such as `ncycles` and `stats_en`, ideally these should be initialised in a base class.

/CC @cfbolz

**Comment by berkinilbeyi** [comment]
That's right. It makes sense to refactor the common fields to a superclass. I'll make this change when I find some time.

**Comment by snim2** [comment]
I notice some places use `...pc` and some use `fetch_pc()` which is something that might be clarified in a superclass.

Thanks!
